In [19]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(0,100,size=(10, 8)), columns=list('ABCDEFGH'))

#Add some NaN values
df.iloc[3, 3] = np.nan
df.iloc[0, 2] = np.nan
df.iloc[1, 4] = np.nan
df.iloc[6, 3] = np.nan
df.iloc[0, 7] = np.nan

In [20]:
df

    A   B     C     D     E   F   G     H
0  50  64   NaN  68.0  30.0  49  25   NaN
1  68  49  35.0  15.0   NaN  45  82   0.0
2  42  50  28.0  51.0  32.0  69  68  72.0
3  57  65  13.0   NaN  56.0  44  19  58.0
4  10  44  92.0  44.0  75.0  18  48  38.0
5  78  96  11.0  12.0  35.0  91   1  12.0
6  24  80  60.0   NaN   9.0  34  43  33.0
7  28  33  90.0   1.0  31.0  98  46  26.0
8  58  92  26.0  58.0  80.0  60  28  67.0
9  48   5  81.0  26.0  53.0  16  65  12.0

In [24]:
df.style.highlight_min(color='yellow').highlight_max(color='green')

In [25]:
df.style.highlight_min(
    color='yellow').highlight_max(
        color='green').highlight_null(
            null_color="red")

In [26]:
df.style.background_gradient()

In [27]:
df.style.background_gradient(cmap="rainbow")

In [30]:
df.style.bar(color="pink")